### ISSUE TITLE
 Not taking keyboard input

### ISSUE THREAD

**Issue by akandGA** [TigerVNC/tigervnc#1051]
**Describe the bug**

**To Reproduce**

After opening vnc client I see my linux desktop to give userid and password for log-in as expected. However, it does not allow to give any keyboard inputs and hence I can not get into the desktop.

**Expected behavior**
I can give keyboard inputs of userid and password so that I can log into the desktop.

**Screenshots**
<img width="960" alt="vnc1" src="https://user-images.githubusercontent.com/67438309/85930638-e79f9800-b872-11ea-8e9c-b6fb322bd02a.png">

**Client (please complete the following information):**
 - OS: Windows 10 (I see same behavior even opening from RHEL7.5)
 - VNC client: TigerVNC
 - VNC client version: 1.8.0
 - Client downloaded from: https://tigervnc.org/

**Server (please complete the following information):**
 - OS: RHEL7.5
 - VNC server: TigerVNC
 - VNC server version: 1.8.0
 - Server downloaded from: https://tigervnc.org/
 - Server was started using: `vncserver`

**Additional context**
The attachment shows xstartup and config files (vnc1.zip). We have RHEL7.5. The process Xvnc shows:
webery 40212 1 0 11:14 pts/0 00:00:02 /usr/bin/Xvnc :1 -auth /home/webery/.Xauthority -desktop gpu01.cluster.com:1 (webery) -fp catalogue:/etc/X11/fontpath.d -geometry 1024x768 -pn -rfbauth /home/webery/.vnc/passwd -rfbport 5901 -rfbwait 30000
[vnc1.zip](https://github.com/TigerVNC/tigervnc/files/4841134/vnc1.zip)

**Comment by samhed** [comment]
Could you try with the latest server? 1.8.0 is quite old

**Comment by samhed** [comment]
And the latest viewer as well while you're at it

**Comment by CendioOssman** [comment]
This looks like an old bug in GNOME. I thought it was fixed in something as recent as RHEL 7.5 though.

@akandGA, could you test a nightly build of the TigerVNC server? We've done some major changes to how sessions are started to solve issues like this.

**Comment by akandGA** [comment]
CendioOssman: Please provide download link to collect. Is it https://bintray.com/tigervnc/beta?
samhed: Is 1.10.1 latest version for linux server?

**Comment by samhed** [comment]
Nightly builds are available here: http://tigervnc.bphinz.com/nightly/

1.10.1 is the latest release, but as @CendioOssman mentioned, it might be better to test the nightly build.

**Comment by akandGA** [comment]
When I tried to install tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm, it asked for tigervnc-server-minimal. I installed the tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm. However, still shows same failure. See below:

[root@gpu01 webery]# rpm -i tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm
warning: tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 4582a460: NOKEY
error: Failed dependencies:
        tigervnc-server-minimal = 1.10.80-5.20200608gitda1ce978.el7 is needed by tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64
[root@gpu01 webery]# rpm -i tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm
warning: tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 4582a460: NOKEY
        file /usr/bin/Xvnc from install of tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64 conflicts with file from package tigervnc-server-minimal-1.8.0-17.el7.x86_64
        file /usr/bin/vncconfig from install of tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64 conflicts with file from package tigervnc-server-minimal-1.8.0-17.el7.x86_64
        file /usr/bin/vncpasswd from install of tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64 conflicts with file from package tigervnc-server-minimal-1.8.0-17.el7.x86_64
        file /usr/share/man/man1/Xvnc.1.gz from install of tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64 conflicts with file from package tigervnc-server-minimal-1.8.0-17.el7.x86_64
        file /usr/share/man/man1/vncconfig.1.gz from install of tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64 conflicts with file from package tigervnc-server-minimal-1.8.0-17.el7.x86_64
        file /usr/share/man/man1/vncpasswd.1.gz from install of tigervnc-server-minimal-1.10.80-5.20200608gitda1ce978.el7.x86_64 conflicts with file from package tigervnc-server-minimal-1.8.0-17.el7.x86_64
[root@gpu01 webery]# rpm -i tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm
warning: tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 4582a460: NOKEY
error: Failed dependencies:
        tigervnc-server-minimal = 1.10.80-5.20200608gitda1ce978.el7 is needed by tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64
[root@gpu01 webery]#

Regards,
Akand

**Comment by bphinz** [comment]
Uninstall all of the 1.8.0 packages first.

-brian

**Comment by akandGA** [comment]
I have installed tigervnc-server-1.10.80-5.20200608gitda1ce978.el7.x86_64.rpm (of course the other dependencies it asked for). However, when I execute "vncserver" in order for launching the server it does not find anything. What I am missing?

**Comment by akandGA** [comment]
Brian: Yes I uninstalled 1.8.0 packages. See my comment above.

**Comment by bphinz** [comment]
vncserver is being deprecated in favor of a systemd approach.  A user wrote
up a nice summary of how to use it here:

https://www.reddit.com/r/CentOS/comments/g7j9so/tigervnc_working_on_centos_linux_release_771908/

**Comment by akandGA** [comment]
Thanks. Following the steps this is what I get:

[root@gpu01 tigervnc]# systemctl enable vncserver@:3.service
Created symlink from /etc/systemd/system/multi-user.target.wants/vncserver@:3.service to /etc/systemd/system/vncserver@.service.
[root@gpu01 tigervnc]# systemctl start vncserver@:3.service
Job for vncserver@:3.service failed because the control process exited with error code. See "systemctl status vncserver@:3.service" and "journalctl -xe" for details.
[root@gpu01 tigervnc]# systemctl status vncserver@:3.service
   vncserver@:3.service - Remote desktop service (VNC)
   Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2020-07-06 11:00:04 CDT; 43s ago
  Process: 16456 ExecStart=/usr/libexec/vncsession-start %i (code=exited, status=1/FAILURE)

Jul 06 11:00:04 gpu01.cluster.com systemd[1]: Starting Remote desktop service (VNC)...
Jul 06 11:00:04 gpu01.cluster.com vncsession-start[16456]: No user configured for display :3
Jul 06 11:00:04 gpu01.cluster.com systemd[1]: vncserver@:3.service: control process exited, code=exited status=1
Jul 06 11:00:04 gpu01.cluster.com systemd[1]: Failed to start Remote desktop service (VNC).
Jul 06 11:00:04 gpu01.cluster.com systemd[1]: Unit vncserver@:3.service entered failed state.
Jul 06 11:00:04 gpu01.cluster.com systemd[1]: vncserver@:3.service failed.

**Comment by CendioOssman** [comment]
It seems you missed the step of configuring `/etc/tigervnc/vncserver.users`. Please have a look at that and it should hopefully work better.

**Comment by akandGA** [comment]
**It seems the vncserver has started (at least with no error).**

[root@gpu01 ~]# systemctl daemon-reload
[root@gpu01 ~]# systemctl enable vncserver@:3.service
[root@gpu01 ~]# systemctl start vncserver@:3.service
[root@gpu01 ~]# systemctl status vncserver@:3.service
   vncserver@:3.service - Remote desktop service (VNC)
   Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2020-07-07 19:20:51 CDT; 13s ago
  Process: 12525 ExecStart=/usr/libexec/vncsession-start %i (code=exited, status=0/SUCCESS)
 Main PID: 12530 (code=exited, status=0/SUCCESS)

Jul 07 19:20:51 gpu01.cluster.com systemd[1]: Starting Remote desktop service (VNC)...
Jul 07 19:20:51 gpu01.cluster.com systemd[1]: Started Remote desktop service (VNC).

**Now when I look for the Xvnc running, by ps -ef|grep Xvnc, none shows up. When I check the log file, it says:**
[webery@gpu01 .vnc]$ cat gpu01.cluster.com:3.log
Could not find a desktop session to run

**The config file is:**
[webery@gpu01 .vnc]$ cat  /etc/tigervnc/vncserver-config-defaults
## Default settings for VNC servers started by the vncserver service
#
# Any settings given here will override the builtin defaults, but can
# also be overriden by ~/.vnc/config and vncserver-config-mandatory.
#
# See the following manpages for more details: vncserver(1) Xvnc(1)
#
# Several common settings are shown below. Uncomment and modify to your
# liking.

# securitytypes=vncauth,tlsvnc
# desktop=sandbox
 geometry=2000x1200
 gpu01.cluster.com
# localhost
# alwaysshared

**So, as expected I am unable to open any session by vncviewer.**

**Comment by akandGA** [comment]
It seems the vncserver has started (at least with no error).

[root@gpu01 ~]# systemctl daemon-reload
[root@gpu01 ~]# systemctl enable vncserver@:3.service
[root@gpu01 ~]# systemctl start vncserver@:3.service
[root@gpu01 ~]# systemctl status vncserver@:3.service
vncserver@:3.service - Remote desktop service (VNC)
Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
Active: inactive (dead) since Tue 2020-07-07 19:20:51 CDT; 13s ago
Process: 12525 ExecStart=/usr/libexec/vncsession-start %i (code=exited, status=0/SUCCESS)
Main PID: 12530 (code=exited, status=0/SUCCESS)

Jul 07 19:20:51 gpu01.cluster.com systemd[1]: Starting Remote desktop service (VNC)...
Jul 07 19:20:51 gpu01.cluster.com systemd[1]: Started Remote desktop service (VNC).

Now when I look for the Xvnc running, by ps -ef|grep Xvnc, none shows up. When I check the log file, it says:
[webery@gpu01 .vnc]$ cat gpu01.cluster.com:3.log
Could not find a desktop session to run

The config file is:
[webery@gpu01 .vnc]$ cat  /etc/tigervnc/vncserver-config-defaults
## Default settings for VNC servers started by the vncserver service
#
# Any settings given here will override the builtin defaults, but can
# also be overriden by ~/.vnc/config and vncserver-config-mandatory.
#
# See the following manpages for more details: vncserver(1) Xvnc(1)
#
# Several common settings are shown below. Uncomment and modify to your
# liking.

# securitytypes=vncauth,tlsvnc
# desktop=sandbox
 geometry=2000x1200
 gpu01.cluster.com
# localhost
# alwaysshared

So, as expected I am unable to open any session by vncviewer.

**Comment by akandGA** [comment]
[vncserver-config-defaults.txt](https://github.com/TigerVNC/tigervnc/files/4887815/vncserver-config-defaults.txt)

**Comment by akandGA** [comment]
As I mentioned in my above comment that following the steps the vncserver has started, but the logfile says "Could not find a desktop session to run".

What can be possible reason of this?

Thanks.

**Comment by CendioOssman** [comment]
It means it didn't find any desktop environment on your system, which is a bit odd. What's the contents of `/usr/share/xsessions/` on this server?

**Comment by akandGA** [comment]
Nothing is in /usr/share/xsessions/

**Comment by CendioOssman** [comment]
In that case I'm afraid the error message is correct. You have no desktop environments installed. It seems something is partially installed though as you were able to get xstartup to run something. Please do `yum install @GNOME` and see if that gets things going.

**Comment by akandGA** [comment]
Some advancement. Now I can log in (at least). The desktop does not show any apps (except system related). If I search for "terminal" nothing shows up. 
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/67438309/87488885-637d3c80-c5f6-11ea-8bfd-d1d510854ac6.png">

**Comment by CendioOssman** [comment]
Given that your desktop environment wasn't fully installed, I would guess that the reason you don't see any terminal is that no terminal is installed.

Everything seems to be working fine from a TigerVNC perspective now, so I'm afraid you'll have to direct any further questions about the desktop to Red Hat.

**Comment by akandGA** [comment]
I didn't know that gnome requires separate installations of terminal, etc. Now, everything is fine as it should. Thank you everyone!
