### ISSUE TITLE
TigerVNC 1.5.0 upgrade leads to keyboard/mouse interaction loss

### ISSUE THREAD

**Issue by durack1** [TigerVNC/tigervnc#196]
I've just updated from `TigerVNC 1.4.3` to `1.5.0` and some weird new problems have occurred.

`1.4.3` used to work fine, however with `1.5.0` I've started to experience timeouts, when after a relatively short period of time (~minutes) keyboard and mouse interactivity no longer has an effect on the screen/active VNC session. The only solution that I've determined is to close the current `VNC` session (the client) and reconnect again, after which I experience the timeout again after ~minutes. Curiously using the `Ctrl-Alt-Delete` button on the viewer sometimes gets interactively back, just briefly, before losing it again.

I'm using `RealVNC Viewer 5.2.3` for `OS X`, on a host that's running `redhat 6.7`

I noted a [post that indicated updating `libX11` could potentially solve the problem](http://superuser.com/questions/682287/vnc-console-does-not-accept-any-keyboard-mouse-inputs), however I'm patched up and have the latest `redhat 6.7` official:

```
[user@ocean ~]$ sudo yum install libX11
Loaded plugins: changelog, product-id, refresh-packagekit, rhnplugin, security, subscription-manager, versionlock
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Install Process
Package libX11-1.6.0-6.el6.x86_64 already installed and latest version
Nothing to do
```

Anyone got any tips for me here - I'm reluctant to deprecate the install back to `1.4.3` but will have to if I can't find a solution..

I might add I'm more than happy to provide additional diagnostics to get to the bottom of this issue!

**Comment by durack1** [comment]
After further investigations, it seems that screen refreshes are the issue - so upon restarting the client, windows that I have inadvertently clicked (even though I saw no visual response) are changed.. So this is a refresh issue it seems..

Any suggestions/additional queries for further diagnostics are very welcome!

**Comment by CendioOssman** [comment]
Do you see this if you use our client?

**Comment by durack1** [comment]
Is there a `OS X` viewer available? I couldn't see one downloadable from https://bintray.com/tigervnc/stable/tigervnc/1.5.0

**Comment by bphinz** [comment]
On Fri, Sep 18, 2015 at 1:50 PM, Paul J. Durack <notifications@github.com>
wrote:

> Is there a OS X viewer available? I couldn't see one downloadable from
> https://bintray.com/tigervnc/stable/tigervnc/1.5.0
>
Yes, it's on the page that you referenced.  I think the issue you're seeing
is the same thing that several others have reported.  I can easily
reproduce something similar by trying to run the generic binaries on a
CentOS 6.7 system, but so far have not been able to identify the cause.
The problem seems to be on the server side, as it occurs on different
platforms and with both the native and Java viewers.

-brian

**Comment by durack1** [comment]
@bphinz @CendioOssman if there are any diagnostics you folks need from a machine with the problem currently occurring I'm more than happy to generate these..

**Comment by durack1** [comment]
Curiously, if I turn off the option in the `RealVNC client` to "Adapt to network speed" and set my compression to "Hundreds of colors" the problem appears to disappear.. At least during my continuing usage today..

**Comment by bphinz** [comment]
On Mon, Sep 21, 2015 at 7:32 PM, Paul J. Durack <notifications@github.com>
wrote:

> Curiously, if I turn off the option in the RealVNC client to "Adapt to
> network speed" and set my compression to "Hundreds of colors" the problem
> appears to disappear.. At least during my continuing usage today..
>
Keen observation Paul.

Pierre - this issue is somehow related to color depth.  In 8-bit color mode
things seem to run fine.  In TrueColor mode screen refreshes seem to stop
almost immediately after the initial screen draw.

-brian

**Comment by CendioOssman** [comment]
I'm afraid I'm unable to reproduce this when I'm testing. I used RealVNC 5.2.3 on OS X against my Xvnc build on a Fedora 22. Is it only the generic builds that are affected?

**Comment by bphinz** [comment]
On Tue, Sep 22, 2015 at 4:48 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> I'm afraid I'm unable to reproduce this when I'm testing. I used RealVNC
> 5.2.3 on OS X against my Xvnc build on a Fedora 22. Is it only the generic
> builds that are affected?
>
I have only been able to reproduce it with the generic builds, but we've
seen emails and issues opened that describe the similar problems with the
el6 and debian builds within the last couple of months.

Can you try adding some network latency?  I found that with even a
relatively small amount (like a client connecting wirelessly) makes the
problem occur almost immediately 100% of the time with full color depth,
and about 50% of the time with 8-bit color.  Under low latency conditions
the problem seems to occur infrequently, and I can pretty much always get
well beyond the initial frame before the updates stop.  I've reproduced
this with the binary and java clients, on multiple platforms, and with
versions going back to 1.3, so it appears to be an issue with the server
rather than the client.

-brian

**Comment by durack1** [comment]
@bphinz network latency is certainly an issue that my configuration deals with.. So your comments are consistent with my issues..

**Comment by CendioOssman** [comment]
> Can you try adding some network latency?

I'll try to sort something out. But it's going to be hell to debug if it only occurs with the generic builds.

> I've reproduced this with the binary and java clients, on multiple platforms, and with versions going back to 1.3, so it appears to be an issue with the server rather than the client.

So you're saying you're seeing this with our clients as well?

**Comment by bphinz** [comment]
On Wed, Sep 23, 2015 at 3:39 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Can you try adding some network latency?
>
> I'll try to sort something out. But it's going to be hell to debug if it
> only occurs with the generic builds.
>
> I've reproduced this with the binary and java clients, on multiple
> platforms, and with versions going back to 1.3, so it appears to be an
> issue with the server rather than the client.
>
> So you're saying you're seeing this with our clients as well?
>
I've only ever tried our clients, so yes.

-brian

**Comment by CendioOssman** [comment]
I've been able to reproduce it here now with our client (my own build of master) against the generic builds. The bug is present even in the nightly build. But I am unable to get any problem with an Xvnc I build myself. So I'm not sure how to debug it...

@bphinz, do you think you can pinpoint what change is triggering the bug? E.g. some hybrid of the generic build and the EL6 build?

**Comment by bphinz** [comment]
On Wed, Sep 23, 2015 at 6:15 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> I've been able to reproduce it here now with our client (my own build of
> master) against the generic builds. The bug is present even in the nightly
> build. But I am unable to get any problem with an Xvnc I build myself. So
> I'm not sure how to debug it...
>
> @bphinz <https://github.com/bphinz>, do you think you can pinpoint what
> change is triggering the bug? E.g. some hybrid of the generic build and the
> EL6 build?
>
Yeah.  Unfortunately, I have the build system configure to only archive 2
weeks worth of nightlies but it shouldn't be too hard to add a parameter
allowing a particular git revision to be specified.  That way I can just
queue up a bunch of builds corresponding to changesets that we think might
be responsible and start testing those.  Give me a couple days to make the
changes and run the builds.

**Comment by CendioOssman** [comment]
Sorry, I meant which change between the EL5 and EL6 build (which I assume works fine). Although a commit to TigerVNC would be nice as well.

But it so happens I've managed to make some bastard build of the EL5 SRPM on EL6. And I think I've pinpointed the issue. Commit f8e3b34c69b848781b958c7a4d21175ddc6f90d8 seems to be the culprit. Let me dig a bit more.

**Comment by CendioOssman** [comment]
Fixed in c88dc80. :)

The triggering condition was using an Xorg base that lacked the `vncWriteBlockHandler()` patch, which is why only some builds were affected.

**Comment by durack1** [comment]
@CendioOssman great! What are the chances that a new `1.5.1` release and new `redhat6` binaries could be dropped up on bintray?

**Comment by CendioOssman** [comment]
That might be a while. But you can grab an updated nightly build right now. Check our main page for the link.

**Comment by durack1** [comment]
@bphinz what is the `nightly` direct comparison to the [`tigervnc-Linux-x86_64-1.5.0.tar.gz`](https://bintray.com/artifact/download/tigervnc/stable/tigervnc-Linux-x86_64-1.5.0.tar.gz) file available from `bintray`?

I'm a little perplexed by the 4 available `RedHat EL6 x86_64` options, and am wondering if [`tigervnc-1.5.80-21.20150925gitc88dc805.el6.x86_64.rpm`](http://tigervnc.bphinz.com/nightly/el6/RPMS/x86_64/tigervnc-1.5.80-21.20150925gitc88dc805.el6.x86_64.rpm) is my closest match? Or whether the `tigervnc-server-*` files are more appropriate?

Or are the `cross-compatible` [x86_64 `tigervnc-Linux-x86_64-1.5.80-20150925gitc88dc805.tar.gz` builds](http://tigervnc.bphinz.com/nightly/xc/x86_64/tigervnc-Linux-x86_64-1.5.80-20150925gitc88dc805.tar.gz) the most directly comparable?

**Comment by bphinz** [comment]
On Fri, Sep 25, 2015 at 1:58 PM, Paul J. Durack <notifications@github.com>
wrote:

> @bphinz <https://github.com/bphinz> what is the nightly direct comparison
> to the tigervnc-Linux-x86_64-1.5.0.tar.gz
> <https://bintray.com/artifact/download/tigervnc/stable/tigervnc-Linux-x86_64-1.5.0.tar.gz>
> file available from bintray?
>
> I'm a little perplexed by the 4 available RedHat EL6 x86_64 options, and
> am wondering if tigervnc-1.5.80-21.20150925gitc88dc805.el6.x86_64.rpm
> <http://tigervnc.bphinz.com/nightly/el6/RPMS/x86_64/tigervnc-1.5.80-21.20150925gitc88dc805.el6.x86_64.rpm>
> is my closest match? Or whether the tigervnc-server-* files are more
> appropriate?
>
No, this is an RPM built specifically for Red Hat/CentOS 6.  The naming
convention was adopted from Red Hat, and necessary in order to allow our
packages to supersede theirs correctly.

> Or are the cross-compatible x86_64
> tigervnc-Linux-x86_64-1.5.80-20150925gitc88dc805.tar.gz builds
> <http://tigervnc.bphinz.com/nightly/xc/x86_64/tigervnc-Linux-x86_64-1.5.80-20150925gitc88dc805.tar.gz>
> the most directly comparable?
>
Yes, but I've been using the nightly builds for debugging and can confirm
that the problem still exists (or at least it did as of a couple days ago…)

**Comment by durack1** [comment]
@bphinz ok, pity the issue still exists.. Should the issue be reopened if it's not resolved by the fix issued by @CendioOssman?

When you believe that the nightly builds have a working fix I'd certainly be keen to update my install and provide feedback for my configuration..

**Comment by bphinz** [comment]
On Sat, Sep 26, 2015 at 10:54 AM, Brian Hinz wrote:

> Yes, but I've been using the nightly builds for debugging and can confirm
> that the problem still exists (or at least it did as of a couple days ago…)
>

My mistake.  It does appear to be resolved.  My test case wasn't
incorporating Pierre's fix.

**Comment by durack1** [comment]
@bphinz thanks for the heads up.. I'll pull down the latest nightlies (which one was the fix implemented in?) and give this a run on my configuration..

**Comment by bphinz** [comment]
I tested the 9/28 build, but I just posted a fresh one for good measure.

-brian

**Comment by durack1** [comment]
@bphinz @CendioOssman I've been using `1.5.80 nightly` for a couple of hours now and it seems to have fixed my persistent issue.. Thanks!
